import { atom } from 'recoil';

// 해당 유저의 카테고리 리스트
const posts = atom({
  key: 'posts',
  default: [ ],
});

export default posts;

/*

 {
      content: '샘플 문구1',
      total_like: 0,
      share_cnt: 0,
      visit_cnt: 0,
      search: true,
      user_id: 1,
      category_id: 97,
      tags: ['서류', '감사'],
      id: 1,
    },
    {
      content: '샘플 문구2',
      total_like: 0,
      share_cnt: 0,
      visit_cnt: 0,
      search: true,
      user_id: 1,
      category_id: 97,
      tags: ['중요'],
      id: 2,
    },
    {
      content: '샘플 문구3',
      total_like: 0,
      share_cnt: 0,
      visit_cnt: 0,
      search: true,
      user_id: 1,
      category_id: 97,
      tags: ['비행기', '사무'],
      id: 3,
    },
    {
      content: '샘플 문구4',
      total_like: 0,
      share_cnt: 0,
      visit_cnt: 0,
      search: true,
      user_id: 1,
      category_id: 97,
      tags: ['나무'],
      id: 4,
    },
    {
      content: '샘플 문구5',
      total_like: 0,
      share_cnt: 0,
      visit_cnt: 0,
      search: true,
      user_id: 1,
      category_id: 97,
      tags: ['책상'],
      id: 5,
    },
    {
      content: '샘플 문구6',
      total_like: 0,
      share_cnt: 0,
      visit_cnt: 0,
      search: true,
      user_id: 1,
      category_id: 97,
      tags: ['의자'],
      id: 6,
    },
    {
      content: '샘플 문구7',
      total_like: 0,
      share_cnt: 0,
      visit_cnt: 0,
      search: true,
      user_id: 1,
      category_id: 97,
      tags: ['에어컨'],
      id: 7,
    },
    {
      content: '샘플 문구8',
      total_like: 0,
      share_cnt: 0,
      visit_cnt: 0,
      search: true,
      user_id: 1,
      category_id: 97,
      tags: ['선풍기'],
      id: 8,
    },
    {
      content: '샘플 문구9',
      total_like: 0,
      share_cnt: 0,
      visit_cnt: 0,
      search: true,
      user_id: 1,
      category_id: 97,
      tags: ['커피'],
      id: 9,
    },
    {
      content: '샘플 문구10',
      total_like: 0,
      share_cnt: 0,
      visit_cnt: 0,
      search: true,
      user_id: 1,
      category_id: 97,
      tags: ['메가'],
      id: 10,
    },
    {
      content: '샘플 문구11',
      total_like: 0,
      share_cnt: 0,
      visit_cnt: 0,
      search: true,
      user_id: 1,
      category_id: 97,
      tags: ['사장'],
      id: 11,
    },
    {
      content: '샘플 문구12',
      total_like: 0,
      share_cnt: 0,
      visit_cnt: 0,
      search: true,
      user_id: 1,
      category_id: 97,
      tags: ['하늘'],
      id: 12,
    },
*/